name: vidExtractor Node.js CI/CD

on: [push, pull_request]

defaults:  
  run:  
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Setup RabbitMQ
      uses: getong/rabbitmq-action@v1.2
      with:
        rabbitmq version: '3-management-alpine'
        host port: 5672
        rabbitmq user: 'merUser'
        rabbitmq password: 'passwordMER'
    - name: Checkout vidExtractor Project
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --dev
      working-directory: src
    - run: npm run build --if-present
      working-directory: src
    
    - run: npm test
      env:
        CI: true