name: Publish vidExtractor Docker image

on:
  pull_request:
    branches:
      - master
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout vidExtractor Project
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: merteam/vidextractor:latest
          repository: merteam/vidextractor
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}